### ISSUE TITLE
Issue with next-plugin-preact

### ISSUE THREAD

**Issue by DeviousLab** [preactjs/prefresh#360]
An issue [vercel/next.js#26826](https://github.com/vercel/next.js/issues/26826) was brought up in the next.js repo where using Next.js 11 with webpack 5 seems to break the using-preact example.
``` info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
Error: Cannot find module 'webpack/lib/dependencies/ConstDependency'
Require stack:
- /home/projects/nextjs-preact-webpack5-a4fygy/node_modules/@prefresh/webpack/src/index.js
- /home/projects/nextjs-preact-webpack5-a4fygy/node_modules/@prefresh/next/src/index.js
- /home/projects/nextjs-preact-webpack5-a4fygy/node_modules/next-plugin-preact/index.js
- /home/projects/nextjs-preact-webpack5-a4fygy/next.config.js
- /home/projects/nextjs-preact-webpack5-a4fygy/node_modules/next/dist/next-server/server/config.js
- /home/projects/nextjs-preact-webpack5-a4fygy/node_modules/next/dist/server/next.js
- /home/projects/nextjs-preact-webpack5-a4fygy/node_modules/next/dist/server/lib/start-server.js
- /home/projects/nextjs-preact-webpack5-a4fygy/node_modules/next/dist/cli/next-dev.js
- /home/projects/nextjs-preact-webpack5-a4fygy/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (https://nextjs-preact-webpack5-a4fygy.jw.staticblitz.com/blitz.70a1ff62a0f0131ac0df3c30faf487fef744ac90.js:6:189728)
    at Function.mod._resolveFilename (/home/projects/nextjs-preact-webpack5-a4fygy/node_modules/next/dist/build/webpack/require-hook.js:4:1855)
    at Function.Module._resolveFilename (/home/projects/nextjs-preact-webpack5-a4fygy/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (https://nextjs-preact-webpack5-a4fygy.jw.staticblitz.com/blitz.70a1ff62a0f0131ac0df3c30faf487fef744ac90.js:6:187342)
    at Module.require (https://nextjs-preact-webpack5-a4fygy.jw.staticblitz.com/blitz.70a1ff62a0f0131ac0df3c30faf487fef744ac90.js:6:190516)
    at i (https://nextjs-preact-webpack5-a4fygy.jw.staticblitz.com/blitz.70a1ff62a0f0131ac0df3c30faf487fef744ac90.js:6:477111)
    at _0x52c652 (https://nextjs-preact-webpack5-a4fygy.jw.staticblitz.com/blitz.70a1ff62a0f0131ac0df3c30faf487fef744ac90.js:11:190288)
    at ReloadPlugin.webpack5 (/home/projects/nextjs-preact-webpack5-a4fygy/node_modules/@prefresh/webpack/src/index.js:60:29)
    at ReloadPlugin.apply (/home/projects/nextjs-preact-webpack5-a4fygy/node_modules/@prefresh/webpack/src/index.js:170:14)
    at createCompiler (/home/projects/nextjs-preact-webpack5-a4fygy/node_modules/next/dist/compiled/webpack/bundle5.js:141349:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/projects/nextjs-preact-webpack5-a4fygy/node_modules/@prefresh/webpack/src/index.js',
    '/home/projects/nextjs-preact-webpack5-a4fygy/node_modules/@prefresh/next/src/index.js',
    '/home/projects/nextjs-preact-webpack5-a4fygy/node_modules/next-plugin-preact/index.js',
    '/home/projects/nextjs-preact-webpack5-a4fygy/next.config.js',
    '/home/projects/nextjs-preact-webpack5-a4fygy/node_modules/next/dist/next-server/server/config.js',
    '/home/projects/nextjs-preact-webpack5-a4fygy/node_modules/next/dist/server/next.js',
    '/home/projects/nextjs-preact-webpack5-a4fygy/node_modules/next/dist/server/lib/start-server.js',
    '/home/projects/nextjs-preact-webpack5-a4fygy/node_modules/next/dist/cli/next-dev.js',
    '/home/projects/nextjs-preact-webpack5-a4fygy/node_modules/next/dist/bin/next'
  ]
} 
```

I attempted to install webpack5 on its own as a dependency to the package,json file in [vercel/next.js#26864](https://github.com/vercel/next.js/pull/26864) but one of the lead developers suggested that the @prefresh/webpack package is using webpack internals that can't be required as they're no longer available.

This issue was mentioned here as well: [preactjs/next-plugin-preact#34](https://github.com/preactjs/next-plugin-preact/issues/34)

**Comment by verydanny** [comment]
I don't have this issue personally. Check out my example repo: https://github.com/verydanny/preact-nextjs-shenanigans

**Comment by JoviDeCroock** [comment]
Should also be solved by #361

**Comment by DeviousLab** [comment]
Thanks for the quick fix @JoviDeCroock but rerunning the nextjs-preact example spits out a new error now: 
```Error: Cannot find module 'webpack/lib/RuntimeGlobals'```

You can see the example here: https://stackblitz.com/edit/nextjs-preact-webpack5-g2hoxu?file=package.json

**Comment by JoviDeCroock** [comment]
@DeviousLab sorry about that was trying to be a bit too fast https://github.com/preactjs/prefresh/pull/362 has you covered

**Comment by DeviousLab** [comment]
That seems to have done the trick! I see no more errors displayed now
