### ISSUE TITLE
Transform options: cannot read property 'ssr' of undefined

### ISSUE THREAD

**Issue by craftedsystems** [preactjs/prefresh#411]
Transform fails if `options` is undefined.

https://github.com/preactjs/prefresh/blob/fa12c8e24de0919c46115b7c89c96f7da87c9cae/packages/vite/src/index.js#L16

Full error log

```sh
vite v2.7.6 building for production...
✓ 0 modules transformed.
[prefresh] Cannot read property 'ssr' of undefined
file: /project-path/index.html
error during build:
TypeError: Cannot read property 'ssr' of undefined
    at Object.transform (/project-path/node_modules/@prefresh/vite/src/index.js:16:68)
    at /project-path/node_modules/rollup/dist/shared/rollup.js:22681:25
```

**Comment by JoviDeCroock** [comment]
When is this undefined :joy: I thought vite 2.7.0 did a breaking change to always make this an object 😅
